# Site settings

title: Pranav Shah  # Title of your site
email: hello@pran.io # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  iOS and Mac Developer with over 6 years of Mobile Development experience looking for freelance work!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "pran.io" # the base hostname & protocol for your site

github_username:      pranavss11  # Replace this with your GitHub username
linkedin_username:    pranav-shah-577aa618  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown
